# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Console App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish project
      run: dotnet publish --configuration Release --output ./published
    - name: shot folder
      run : ls -la
    
  conecction-ssh:
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 172.20.255.15
        username: desarrollo
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
        whoami
        ls -al
        mkdir /home/desarrollo carpeta-git-acction
